# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mumbleapipy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://infocotecnologiaacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7837ce7f68c84e4ab98fa01badb52276 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb69da5c518e4af79136e9ac0308064c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: infocotecnologiaacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7837ce7f68c84e4ab98fa01badb52276 }}/mumbleapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mumbleapipy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ceb10134660c488a9db0026a232f2a79 }}
        images: 'infocotecnologiaacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7837ce7f68c84e4ab98fa01badb52276 }}/mumbleapi:${{ github.sha }}'